---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Body.ResourceGroup.Slug }}
  labels:
    resource-group: {{ .Body.ResourceGroup.ID }}
    company-id: {{ .Body.ResourceGroup.CompanyID }}
    istio-injection: enabled
